title: Its about me!!
author: saurav7007
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 This is awesome to have everyone with me here.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
